// Re-export from shared types and utilities for backward compatibility
// with components generated by Lovable
export type { Variant } from "@/types/products";
export type { SubCategory as Subcategory, Category } from "@/types/products";
export {
  slugify,
  extractEnglishName,
  findProduct,
  getSubcategoryLink,
  getSubcategorySlug,
} from "@/lib/product-utils";