/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsCategoryIdSubcategorySlugRouteImport } from './routes/products.$categoryId.$subcategorySlug'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsCategoryIdSubcategorySlugRoute =
  ProductsCategoryIdSubcategorySlugRouteImport.update({
    id: '/$categoryId/$subcategorySlug',
    path: '/$categoryId/$subcategorySlug',
    getParentRoute: () => ProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/products/$categoryId/$subcategorySlug': typeof ProductsCategoryIdSubcategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/products': typeof ProductsIndexRoute
  '/products/$categoryId/$subcategorySlug': typeof ProductsCategoryIdSubcategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/products/$categoryId/$subcategorySlug': typeof ProductsCategoryIdSubcategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogue'
    | '/products'
    | '/products/'
    | '/products/$categoryId/$subcategorySlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogue'
    | '/products'
    | '/products/$categoryId/$subcategorySlug'
  id:
    | '__root__'
    | '/'
    | '/catalogue'
    | '/products'
    | '/products/'
    | '/products/$categoryId/$subcategorySlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogueRoute: typeof CatalogueRoute
  ProductsRoute: typeof ProductsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$categoryId/$subcategorySlug': {
      id: '/products/$categoryId/$subcategorySlug'
      path: '/$categoryId/$subcategorySlug'
      fullPath: '/products/$categoryId/$subcategorySlug'
      preLoaderRoute: typeof ProductsCategoryIdSubcategorySlugRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsCategoryIdSubcategorySlugRoute: typeof ProductsCategoryIdSubcategorySlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsCategoryIdSubcategorySlugRoute:
    ProductsCategoryIdSubcategorySlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogueRoute: CatalogueRoute,
  ProductsRoute: ProductsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
